# Generated by Django 3.2.16 on 2023-01-24 17:54

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('AE', 'Aerodinâmica'), ('DS', 'Direção e Suspenção'), ('EL', 'Elétrica'), ('ES', 'Estrutura'), ('FR', 'Freio e Ergonomia'), ('PW', 'Powewtrain'), ('CM', 'Comercial'), ('FN', 'Financeiro'), ('GS', 'Gestão de Pessoas'), ('MK', 'Marketing')], max_length=100)),
                ('situacao', models.CharField(choices=[('AF', 'A fazer'), ('FA', 'Fazendo'), ('FE', 'Feito')], max_length=100)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Data do evento', verbose_name='Data')),
                ('start_time', models.TimeField(help_text='Início', verbose_name='Início')),
                ('notes', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Calendário Fast',
                'verbose_name_plural': 'Calendário Fast',
            },
        ),
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('funcao', models.CharField(choices=[('CO', 'Cordenador'), ('AS', 'Assesor'), ('CN', 'Conselheiro'), ('CA', 'Capitão(ã)'), ('VC', 'Vice Capitão(ã)'), ('DP', 'Diretor(a) de Projetos'), ('DA', 'Diretor(a) Administrativo')], max_length=50)),
                ('area', models.CharField(choices=[('AE', 'Aerodinâmica'), ('DS', 'Direção e Suspenção'), ('EL', 'Elétrica'), ('ES', 'Estrutura'), ('FR', 'Freio e Ergonomia'), ('PW', 'Powewtrain'), ('CM', 'Comercial'), ('FN', 'Financeiro'), ('GS', 'Gestão de Pessoas'), ('MK', 'Marketing'), ('NA', 'Nenhuma')], max_length=50)),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='integrantes', variations={}, verbose_name='imagem')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivosArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('AE', 'Aerodinâmica'), ('DS', 'Direção e Suspenção'), ('EL', 'Elétrica'), ('ES', 'Estrutura'), ('FR', 'Freio e Ergonomia'), ('PW', 'Powewtrain'), ('CM', 'Comercial'), ('FN', 'Financeiro'), ('GS', 'Gestão de Pessoas'), ('MK', 'Marketing'), ('NA', 'Nenhuma')], default='Nenhuma', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Regulamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(choices=[('GR - General Regulations', 'General Regulations'), ('AD - Administrative Regulations', 'Administrative Regulations')], max_length=50, verbose_name='T1')),
                ('t3', models.CharField(max_length=100)),
                ('resumo', models.TextField(help_text='Escreva o resumo')),
            ],
            options={
                'verbose_name': 'Regulamento',
                'verbose_name_plural': 'Regulamento',
            },
        ),
    ]
