# Generated by Django 3.2.16 on 2023-01-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230125_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulamento',
            name='t2',
            field=models.CharField(default='Default', max_length=50, verbose_name='Título 2'),
        ),
        migrations.AlterField(
            model_name='regulamento',
            name='t1',
            field=models.CharField(choices=[('GR - General Regulations', 'GR - General Regulations'), ('AD - Administrative Regulations', 'AD - Administrative Regulations'), ('DR - Document Requirements', 'DR - Document Requirements'), ('V - Vehicle Requirements', 'V - Vehicle Requirements'), ('F - Chassis and Structural ', 'F - Chassis and Structural'), ('T - Technical Aspects ', 'T - Technical Aspects'), ('VE - Vehicle and Driver Equipament', 'VE - Vehicle and Driver Equipament'), ('IC - Internal Combustion Engine Vehicles', 'IC - Internal Combustion Engine Vehicles'), ('IN - Technical Inspection', 'IN - Technical Inspection'), ('S - Static Events', 'S - Static Events'), ('D - Dynamic Events', 'D - Dynamic Events')], max_length=50, verbose_name='Título 1'),
        ),
        migrations.AlterField(
            model_name='regulamento',
            name='t3',
            field=models.CharField(default='Default', max_length=100, verbose_name='Título 3'),
        ),
    ]
